<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use Faker\Factory as Faker;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $faker = Faker::create();
        $categories = array(
            array('id' => '1','name' => 'Electronics','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'electronics.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '2','name' => 'Cameras & Accessories','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '3','name' => 'Food & Drink','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'food-drink.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '4','name' => 'Computers & Accessories','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '5','name' => 'Gadgets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '6','name' => 'Gaming','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '7','name' => 'Home Appliances','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '8','name' => 'Kitchen Appliances','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '9','name' => 'Laptops','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '10','name' => 'SIM Free Handsets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '11','name' => 'Tablets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '12','name' => 'TV, Sound & Entertainment','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '13','name' => 'Wearables','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '1','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '14','name' => 'Fashion','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'fashion.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '15','name' => 'Bags','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '16','name' => 'Clothing','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '17','name' => 'Fashion Accessories','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '18','name' => 'Footwear','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '19','name' => 'Lingerie','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '20','name' => 'Sunglasses','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '21','name' => 'Watches & Jewellery','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '14','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '22','name' => 'Drink','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '3','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '23','name' => 'Food & Chocolate','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '3','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '24','name' => 'Pubs & Bars','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '3','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '25','name' => 'Restaurants','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '3','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '26','name' => 'Supermarkets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '3','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '27','name' => 'Takeaway & Delivery','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '3','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '28','name' => 'Health & Beauty','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'health-beauty.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '29','name' => 'Beauty','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '28','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '30','name' => 'Fragrances','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '28','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '31','name' => 'Glasses & Lenses','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '28','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '32','name' => 'Health','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '28','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '33','name' => 'Men\'s Grooming','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '28','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '34','name' => 'Vitamins & supplements','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '28','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '35','name' => 'Home & DIY','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'home-diy.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '36','name' => 'Bathroom & Accessories','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '35','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '37','name' => 'Beds & Bedding','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '35','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '38','name' => 'DIY','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '35','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '39','name' => 'Garden','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '35','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '40','name' => 'Homewares','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '35','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '41','name' => 'Other','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'other.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '42','name' => 'Auction & Selling','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '43','name' => 'Cars','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '44','name' => 'Car Accessories','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '43','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '45','name' => 'Car Rental','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '43','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '46','name' => 'Car Sales & Services','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '43','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '47','name' => 'Charity','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '48','name' => 'Department Stores','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '49','name' => 'Entertainment','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '50','name' => 'Adult','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '51','name' => 'Ancestry','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '52','name' => 'Attractions & Experiences','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '53','name' => 'Books & Mags','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '54','name' => 'Daily Deals','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '55','name' => 'Dating','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '56','name' => 'Fancy Dress','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '57','name' => 'Gambling','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '58','name' => 'Games','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '59','name' => 'Movies','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '60','name' => 'Music','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '61','name' => 'Personalised Cards','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '62','name' => 'Surveys & Competitions','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '63','name' => 'Tickets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '49','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '64','name' => 'Finance','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '65','name' => 'Finance','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '64','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '66','name' => 'Insurance','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '67','name' => 'Insurance','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '66','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '68','name' => 'Office & Business','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '69','name' => 'Advertising & Research','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '68','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '70','name' => 'Business Insurance','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '68','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '71','name' => 'Business Services','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '68','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '72','name' => 'Delivery Services','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '68','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '73','name' => 'Office','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '68','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '74','name' => 'Training & Recruitment','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '68','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '75','name' => 'Parent & Kids','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '76','name' => 'Maternity Wear','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '75','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '77','name' => 'Pets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '78','name' => 'Utilities','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '41','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '79','name' => 'Gas & Electricity','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '78','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '80','name' => 'Sports & Fitness','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'sports-fitness.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '81','name' => 'Telecoms','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '82','name' => 'Broadband','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '81','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '83','name' => 'Digital TV','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '81','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '84','name' => 'Landline Phone','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '81','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '85','name' => 'Mobiles','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '81','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '86','name' => 'Gifts','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'gifts.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '87','name' => 'Drink','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '86','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '88','name' => 'Flowers','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '86','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '89','name' => 'Food & Chocolate','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '86','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '90','name' => 'Gadgets','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '86','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '91','name' => 'Personalised Cards','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '86','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '92','name' => 'Toys','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '86','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '93','name' => 'Travel','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'travel.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '94','name' => 'Accommodation','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '95','name' => 'Car Rental','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '96','name' => 'Ferries and Cruises','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '97','name' => 'Flights','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '98','name' => 'Holidays','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '99','name' => 'Parking & Transfers','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '100','name' => 'Rail & Coach','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '94','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '101','name' => 'Cashback To Your Door','description' => 'With Cashback To Your Door, you can discover local restaurants and grocery stores to order African, Caribbean or from any other authentic Black-owned vendors and earn cashback through our partnerships with your favorite delivery apps such as Deliveroo and Uber Eats. Whether there’s rice at home or not, you can be sure that through Cashback To Your Door, you’ll always be able to find local Black-owned retailers for your next order. You can go to Grocery Stores or Restaurants.','sort' => NULL,'logo_type' => 'upload','logo_upload' => 'cashback.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '0','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '102','name' => 'Grocery Stores','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '101','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
            array('id' => '103','name' => 'Restaurants','description' => NULL,'sort' => NULL,'logo_type' => 'upload','logo_upload' => 'category_default_logo.png','logo_link' => NULL,'banner_type' => 'upload','banner_upload' => 'category_default_banner.png','banner_link' => NULL,'parent_id' => '101','status' => '1','created_at' => '2021-05-26 08:38:56','updated_at' => '2021-05-26 08:38:56','deleted_at' => NULL),
        );


        foreach($categories as $cat){
            $category                   = new Category();
            $category->name             = $cat['name'];
            $category->slug             =  \Str::slug($cat['name']);
            $category->description       = 'Browse our best offers, including exclusive cashback deals increased for a limited time only.';
            $category->parent_id        = $cat['parent_id'];
            $category->logo_type        = 'upload';
            $category->logo_upload      = $cat['logo_upload'];
            $category->banner_type      = 'upload';
            $category->banner_upload    = 'category_default_banner.png';
            $category->feature_homepage = ($cat['parent_id'] == 0) ? $faker->randomElement($array = array ('1','0')) : 0;
            $category->feature_sidebar = ($cat['parent_id'] == 0) ? $faker->randomElement($array = array ('1','0')) : 0;
            $category->save();
        }

    }
}
