<?php

namespace Database\Seeders;

use Carbon\Carbon;
use App\Models\Category;
use Faker\Factory as Faker;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        $categories = array(
            array('name' => 'Electronics', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'electronics.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Cameras & Accessories', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Food & Drink', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'food-drink.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Computers & Accessories', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Gadgets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Gaming', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Home Appliances', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Kitchen Appliances', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Laptops', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'SIM Free Handsets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Tablets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'TV, Sound & Entertainment', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Wearables', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '1', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Fashion', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'fashion.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Bags', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Clothing', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Fashion Accessories', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Footwear', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Lingerie', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Sunglasses', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Watches & Jewellery', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '14', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Drink', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '3', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Food & Chocolate', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '3', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Pubs & Bars', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '3', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Restaurants', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '3', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Supermarkets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '3', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Takeaway & Delivery', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '3', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Health & Beauty', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'health-beauty.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Beauty', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '28', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Fragrances', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '28', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Glasses & Lenses', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '28', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Health', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '28', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Men\'s Grooming', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '28', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Vitamins & supplements', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '28', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Home & DIY', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'home-diy.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Bathroom & Accessories', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '35', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Beds & Bedding', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '35', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'DIY', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '35', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Garden', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '35', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Homewares', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '35', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Other', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'other.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Auction & Selling', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Cars', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Car Accessories', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '43', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Car Rental', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '43', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Car Sales & Services', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '43', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Charity', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Department Stores', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Entertainment', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Adult', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Ancestry', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Attractions & Experiences', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Books & Mags', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Daily Deals', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Dating', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Fancy Dress', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Gambling', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Games', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Movies', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Music', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Personalised Cards', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Surveys & Competitions', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Tickets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '49', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Finance', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Finance', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '64', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Insurance', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Insurance', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '66', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Office & Business', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Advertising & Research', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '68', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Business Insurance', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '68', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Business Services', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '68', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Delivery Services', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '68', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Office', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '68', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Training & Recruitment', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '68', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Parent & Kids', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Maternity Wear', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '75', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Pets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Utilities', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '41', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Gas & Electricity', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '78', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Sports & Fitness', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'sports-fitness.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Telecoms', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Broadband', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '81', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Digital TV', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '81', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Landline Phone', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '81', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Mobiles', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '81', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Gifts', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'gifts.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Drink', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '86', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Flowers', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '86', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Food & Chocolate', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '86', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Gadgets', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '86', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Personalized Cards', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '86', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Toys', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '86', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Travel', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'travel.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Accommodation', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Car Rental', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Ferries and Cruises', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Flights', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Holidays', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Parking & Transfers', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Rail & Coach', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '94', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Cashback To Your Door', 'description' => 'With Cashback To Your Door, you can discover local restaurants and grocery stores to order African, Caribbean or from any other authentic Black-owned vendors and earn cashback through our partnerships with your favorite delivery apps such as Deliveroo and Uber Eats. Whether there’s rice at home or not, you can be sure that through Cashback To Your Door, you’ll always be able to find local Black-owned retailers for your next order. You can go to Grocery Stores or Restaurants.', 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'cashback.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '0', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Grocery Stores', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '101', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Restaurants', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '101', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Car Rental', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Ferries & Cruiselines', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Flights', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Hotel & Accommodation', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Package Holidays', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Rail & Coach', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
            array('name' => 'Transfers & Airport Parking ', 'description' => NULL, 'sort' => NULL, 'logo_type' => 'upload', 'logo_upload' => 'category_default_logo.png', 'logo_link' => NULL, 'banner_type' => 'upload', 'banner_upload' => 'category_default_banner.png', 'banner_link' => NULL, 'parent_id' => '93', 'status' => '1', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(), 'deleted_at' => NULL),
        );

        foreach ($categories as $cat) {
            $category = new Category();
            $category->name = $cat['name'];
            $category->slug =  Str::slug($cat['name']);
            $category->description = 'Browse our best offers, including exclusive cashback deals increased for a limited time only.';
            $category->parent_id = $cat['parent_id'];
            $category->logo_type = 'upload';
            $category->logo_upload = $cat['logo_upload'];
            $category->banner_type = 'upload';
            $category->banner_upload = 'category_default_banner.png';
            $category->feature_homepage = ($cat['parent_id'] == 0) ? $faker->randomElement($array = array('1', '0')) : 0;
            $category->feature_sidebar = ($cat['parent_id'] == 0) ? $faker->randomElement($array = array('1', '0')) : 0;
            $category->save();
        }
    }
}
